apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  app.properties: |
    environment=production
    log_level=info
    enable_metrics=true
    metrics_port=9090
  
  database.properties: |
    max_connections=100
    connection_timeout=30
    query_timeout=10